### get random bestemmia
GET {{url}}
Accept: application/json


### create bestemmia
POST {{url}}
Accept: application/json
Content-Type: application/json

{
  "bestemmia": "dio {{$random.alphabetic(25)}}"
}

### delete bestemmia
DELETE {{url}}?id=2
Accept: application/json
